### ISSUE TITLE
How to unlock offline game content?

### ISSUE THREAD

**Issue by SeruiosBoss** [thethiny/MK11-VR-Hasher#1]
Empress hacked the game .. how to open all the items and costumes with the hacked game? content? Answer me.

Can you share your save file? I really want to) Sorry for being a pirate) I don't have 60 bucks for the game, I will be grateful

**Comment by thethiny** [comment]
Cracked version uses offline mode. Game doesn't save in offline mode. Unlocking stuff in offline mode doesn't need an unlocker, it needs a coalesced mod. I will see about that later when the November update is here.

**Comment by SeruiosBoss** [comment]
Thx, but can't the save file help? I want it as quickly as possible

пт, 23 окт. 2020 г. в 19:37, thethiny <notifications@github.com>:

**Comment by thethiny** [comment]
There isn't a save file for MK11.

**Comment by SeruiosBoss** [comment]
MK11PSET_2020-10-23_11
MK11GSET
but what is this?..(

пт, 23 окт. 2020 г. в 20:21, thethiny <notifications@github.com>:

**Comment by SeruiosBoss** [comment]
if I pass the game and the towers, won't they give me things?

пт, 23 окт. 2020 г. в 20:28, Seruios Company <seruioscompany@gmail.com>:

**Comment by thethiny** [comment]
They will go after you restart

**Comment by SeruiosBoss** [comment]
sad( can you offer\advise\suggest a solution me\ something?  or now it's
impossible?

пт, 23 окт. 2020 г. в 20:38, thethiny <notifications@github.com>:

**Comment by thethiny** [comment]
You have to edit coalesced.ini and unlock everything.

**Comment by SeruiosBoss** [comment]
But how to do it? There are only strange symbols in coalesced.ini. ?

пт, 23 окт. 2020 г. в 21:18, thethiny <notifications@github.com>:

**Comment by SeruiosBoss** [comment]
Can u help? should I decrypt it first?


пт, 23 окт. 2020 г. в 22:50, Seruios Company <seruioscompany@gmail.com>:

**Comment by SeruiosBoss** [comment]
I'm sorry to bother you, but is it possible right now or do I need to wait
for you?

сб, 24 окт. 2020 г. в 10:38, Seruios Company <seruioscompany@gmail.com>:

**Comment by thethiny** [comment]
You need to download dfpslayer from github, use it on the coalesced, then use MKX coalesced tools to extract the coalesced and edit it.

**Comment by SeruiosBoss** [comment]
Okay, thx, Should I edit decrypted coalesced.ini or only files
under $ConfigDir$? And how to edit files for unlock skins? costumes?

вс, 25 окт. 2020 г. в 18:34, thethiny <notifications@github.com>:

**Comment by SeruiosBoss** [comment]
can i find out how to open at least 1 skin before you make a mod?

вс, 25 окт. 2020 г. в 20:09, Seruios Company <seruioscompany@gmail.com>:

**Comment by SeruiosBoss** [comment]
I found NOO_Skin501_Palette1_Level1 in coalesced.eng - is 1 of noob skins.
How should I add it to unlocked skins? Should I somehow open CHAR_Noo.xxx
file? Or just edit somehow coalesced.ini? Can u help pls?(

**Comment by SeruiosBoss** [comment]
[CHAR_Spawn.mAssetDefinition]
mPaletteKey=SPA
mCharScript=CHAR_Spawn.mko
mCharScriptAssetPackage=CHAR_SPA_ScriptAssets
mCharCommonScriptAssetPackage=CHAR_SPA_ScriptAssets
mCharacterAssetPath=
DLC.Spawn.Characters.CHAR.SPA.SPA_ASSET.SPA_CharacterAsset
mCAPDefinitionsPath=DLC.Spawn.Characters.CHAR.SPA.SPA_ASSET.SPA_CapAsset
mAssetRootPath=DLC.Spawn.Characters.CHAR
mDefaultPreset=SPA_DefaultPreset
mCAPPackages=("GearAssets_SPA_ScriptAssets")
mCharPackages=("CHAR_SPA_ScriptAssets") I Found this. Should I only edit
coalesced.ini for costumes and skins? or should I find a Character file
with his unlocked costumes? Please help if u can/..

вс, 25 окт. 2020 г. в 21:55, Seruios Company <seruioscompany@gmail.com>:

> I found NOO_Skin501_Palette1_Level1 in coalesced.eng - is 1 of noob skins.
> How should I add it to unlocked skins? Should I somehow open CHAR_Noo.xxx
> file? Or just edit somehow coalesced.ini? Can u help pls?(
>

**Comment by thethiny** [comment]
You will find the skins in coalesced.eng like you found the noob one, then you copy the name to coalesced.ini, you will find some skins in coalesced.ini that are already unlocked.

**Comment by SeruiosBoss** [comment]
I tried to find but can't

пн, 26 окт. 2020 г. в 15:59, thethiny <notifications@github.com>:

**Comment by SeruiosBoss** [comment]
Are u sure? There isn't any unlocked skin in coalesced ini , I tried to
find this place 3 times and again now, I can't find, if it's really can u
say me which code line is this place?

пн, 26 окт. 2020 г. в 19:56, Seruios Company <seruioscompany@gmail.com>:

**Comment by SeruiosBoss** [comment]
No.. I tried so hard to find again but there is only
mCharacters=(mID=CHAR_Raiden, mCharacterKey=RAI, mContentFlags=
(kCIF_IsUnlocked, kCIF_IsCustomCharacter, kCIF_IsSoakable),
mBaseCAPAttributes=DefaultBaseCAPAttributes, mSkeletalSize=
kSkel_Large_Male, mNumCharacterTrials=0, mAssetDefinitionTemplate="
CHAR.Template.mAssetDefinition", mSortOrder=230,
mCharacterAttributes=(Raiden, Male, God, Earthrealmer, WhiteLotus))
THIS codes with characters.

пн, 26 окт. 2020 г. в 20:03, Seruios Company <seruioscompany@gmail.com>:

**Comment by SeruiosBoss** [comment]
There are 2 already unlocked skins -
RAI_Skin0_Level1
RAI_Skin1_Palette6_Level1 - in coalesced eng
but there isn't the same costumes in coalesced.ini
Where can I find a place with already unlocked skins?(

пн, 26 окт. 2020 г. в 20:16, Seruios Company <seruioscompany@gmail.com>:

**Comment by SeruiosBoss** [comment]
Damn, it's impossible even if you don't know 😭 ((

пн, 26 окт. 2020 г. в 20:31, Seruios Company <seruioscompany@gmail.com>:

**Comment by SeruiosBoss** [comment]
maybe this? -
C:\Jen_noAV\711_prod_S\MK11Game\Config\DefaultCensoringDatabase.ini=1578067333.000000
But how top open it?

пн, 26 окт. 2020 г. в 20:43, Seruios Company <seruioscompany@gmail.com>:

**Comment by thethiny** [comment]
You will find the default skins, just search for RAI_ and you will see. If it's not there then maybe they changed it in the update and even that will not work.

**Comment by SeruiosBoss** [comment]
yes.. it's not there( what can I do then?

пн, 26 окт. 2020 г. в 21:06, thethiny <notifications@github.com>:

**Comment by SeruiosBoss** [comment]
I checked 2019 coalesced.ini and default costumes also aren't there..(

пн, 26 окт. 2020 г. в 21:26, Seruios Company <seruioscompany@gmail.com>:

**Comment by SeruiosBoss** [comment]
I Found DefaultUnlocks in MK11ItemDatabase.XXX, but I can't open or edit
this. How to encrypt?

пн, 26 окт. 2020 г. в 21:33, Seruios Company <seruioscompany@gmail.com>:

**Comment by SeruiosBoss** [comment]
How to open unp file?

пн, 26 окт. 2020 г. в 21:45, Seruios Company <seruioscompany@gmail.com>:

**Comment by SeruiosBoss** [comment]
Just, Can I unlock costumes with Cheat Engine? Already patched the game,
Cheat Engine works, I tried to hack game but I could only change Name of
costume, not change costume ( . What should I do to find items in memory?..

пн, 26 окт. 2020 г. в 22:15, Seruios Company <seruioscompany@gmail.com>:

**Comment by SeruiosBoss** [comment]
do you can\know about get items with cheat engine, or no?

вт, 27 окт. 2020 г. в 13:50, Seruios Company <seruioscompany@gmail.com>:

**Comment by SeruiosBoss** [comment]
I'm sorry for bothering you


вт, 27 окт. 2020 г. в 18:36, Seruios Company <seruioscompany@gmail.com>:

**Comment by SeruiosBoss** [comment]
a lot of messages( but you're the smartest genius I've found

вт, 27 окт. 2020 г. в 19:44, Seruios Company <seruioscompany@gmail.com>:

**Comment by SeruiosBoss** [comment]
can u help?

вт, 27 окт. 2020 г. в 19:44, Seruios Company <seruioscompany@gmail.com>:

**Comment by SeruiosBoss** [comment]
Any solution please? Cheat Engine or coalesced?//(.. ... (

ср, 28 окт. 2020 г. в 17:42, Seruios Company <seruioscompany@gmail.com>:

**Comment by thethiny** [comment]
In the MK11ItemDatabase you don't need to edit, you just find the skins, then you unlock them in the coalesced. I forgot exactly how to unlock them but maybe you can change the DefaultLoadout or something like that.

**Comment by SeruiosBoss** [comment]
I can't find any DefaultLoadout , should it be in coalesced or is it a different file?

**Comment by SeruiosBoss** [comment]
?
check github

вт, 3 нояб. 2020 г. в 02:16, thethiny <notifications@github.com>:

**Comment by SeruiosBoss** [comment]
I'm sorry thethiny, didn't you find any way to unlock all in offline mode?

чт, 5 нояб. 2020 г. в 11:28, Seruios Company <seruioscompany@gmail.com>:

**Comment by SeruiosBoss** [comment]
??

**Comment by SeruiosBoss** [comment]
Can you answer me? PLS, didn't you already crack f9ckin offline mk11 for
all items?

сб, 28 нояб. 2020 г. в 15:34, Seruios Company ***@***.***>:

**Comment by thethiny** [comment]
No I did not crack offline mk11 content

**Comment by SeruiosBoss** [comment]
Oh sad. Ok, thx. is it impossible?

пн, 22 мар. 2021 г., 18:10 thethiny ***@***.***>:

**Comment by karthik20066002** [comment]
Sorry to wake up a closed thread but can you please explain a little bit elaborately , or have you made the mod?

**Comment by ridhwan-saal** [comment]
Can you explain what's your question

**Comment by karthik20066002** [comment]
I also have the cracked version. And I want to unlock everything. Thethiny said he would later make a mod. So has he made it? Or is there any other way to do this?

**Comment by thethiny** [comment]
Sadly I couldn't get the Cracked Version to run with the unlocker, not because the offline version didn't work, but because Fitgirl (or whomever cracked it) did it in such a bad way that nothing of my tools works.

**Comment by karthik20066002** [comment]
EMPRESS. But I see your point. I attempted to edit coalasced but ended up corrupting them. Still, much obliged for replying.Thanks!

**Comment by karthik20066002** [comment]
How do i edit coalesced .ini to get the items? I have the file decrypted.

**Comment by thethiny** [comment]
you can't unlock items from the ini. You have to edit the save file.

**Comment by EDERTEZGEN** [comment]
How do you edit the save file to unlock the skins?

**Comment by hbashton** [comment]
I have the fitgirl repack, it is 100% identical to the original files. Are you sure there is no way to make @thethiny 's unlocker compatible?

**Comment by thethiny** [comment]
> I have the fitgirl repack, it is 100% identical to the original files. Are you sure there is no way to make @thethiny 's unlocker compatible?

aman released the offline unlocker in mksecrets but you need the CODEX FLT. (March 2022).

**Comment by dev-rudran** [comment]
> > I have the fitgirl repack, it is 100% identical to the original files. Are you sure there is no way to make @thethiny 's unlocker compatible?
> 
> aman released the offline unlocker in mksecrets but you need the CODEX FLT. (March 2022).

man could you help me? i want to unlock all fatalities brutalities instantly, do you know how i can do that? i have the flt march 2022. tried using save files but they dont work

**Comment by ridhwan-saal** [comment]
> > > I have the fitgirl repack, it is 100% identical to the original files. Are you sure there is no way to make @thethiny 's unlocker compatible?
> > 
> > 
> > aman released the offline unlocker in mksecrets but you need the CODEX FLT. (March 2022).
> 
> man could you help me? i want to unlock all fatalities brutalities instantly, do you know how i can do that? i have the flt march 2022. tried using save files but they dont work

Use the same version Aman is using. Codex.

**Comment by dev-rudran** [comment]
> Use the same version Aman is using. Codex.

dont really understand what i gotta do, mind explaining a bit more please?

**Comment by thethiny** [comment]
> man could you help me? i want to unlock all fatalities brutalities instantly, do you know how i can do that? i have the flt march 2022. tried using save files but they dont work

I can't link to pirated links but in the thread aman tells you what game version you need.
