### ISSUE TITLE
Can I get VAC ban with your items hack?

### ISSUE THREAD

**Issue by SeruiosBoss** [thethiny/MK11-VR-Hasher#2]
I'm sorry for open issue for this question, but can I get VAC on Steam or it will be just ban in game?

**Comment by thethiny** [comment]
No

**Comment by SeruiosBoss** [comment]
I won't get any kind of ban, right?

**Comment by thethiny** [comment]
Some users get 6 hours mk11 ban but it goes away

**Comment by SeruiosBoss** [comment]
and you still have not been able to hack the offline version?

**Comment by thethiny** [comment]
I'm not trying. Connect online, unlock stuff, then copy the save into the offline version.

**Comment by SeruiosBoss** [comment]
oh ok, thank you.
